name: UD System Login Check (LINE Alert)

on:
  schedule:
    # UTCで04:57 = JST 13:57
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  login-check:
    runs-on: ubuntu-latest

    steps:
      - name: Login and verify UD System
        id: check
        env:
          BASE_URL: https://hu-udsystem.com/gateway/
          LOGIN_URL: https://hu-udsystem.com/gateway/logon/
          USERNAME: ${{ secrets.LOGIN_USERNAME }}
          PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: |
          echo "Fetching CSRF token..."
          CSRF=$(curl -s -c cookies.txt "$BASE_URL" | grep -oP '(?<=name=\"csrfmiddlewaretoken\" value=\").*?(?=\")')
          if [ -z "$CSRF" ]; then
            echo "CSRF token not found"
            echo "fail=true" >> "$GITHUB_OUTPUT"
            echo "reason=CSRF token not found" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Attempting login..."
          RESPONSE=$(curl -s -b cookies.txt -c cookies.txt \
            -d "csrfmiddlewaretoken=${CSRF}&user_id=${USERNAME}&pwd=${PASSWORD}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -e "$BASE_URL" \
            -X POST "$LOGIN_URL" \
            -w "HTTPSTATUS:%{http_code}")

          HTTP_CODE=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS\:.*//g')

          if [ "$HTTP_CODE" = "200" ] && echo "$BODY" | grep -q "ビルダー"; then
            echo "Login successful (keyword 'ビルダー' detected)"
            echo "fail=false" >> "$GITHUB_OUTPUT"
          else
            echo "Login failed (HTTP $HTTP_CODE)"
            echo "fail=true" >> "$GITHUB_OUTPUT"
            echo "reason=HTTP $HTTP_CODE" >> "$GITHUB_OUTPUT"
          fi

      - name: Notify LINE if failed
        if: steps.check.outputs.fail == 'true'
        env:
          TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          TO: ${{ secrets.GROUP_ID }}
          REASON: ${{ steps.check.outputs.reason }}
        run: |
          BODY=$(jq -n --arg to "$TO" --arg msg "UDシステムに接続できません（${REASON:-不明なエラー}）" \
            '{to:$to, messages:[{type:"text", text:$msg}]}')

          curl -sS -X POST "https://api.line.me/v2/bot/message/push" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            -d "$BODY"
