name: UD System Login Check (with holiday skip)

on:
  schedule:
    # UTC 22:50（日〜木）＝ JST 平日 07:50（翌日）
    - cron: '30 22 * * 0-4'
  workflow_dispatch:

jobs:
  login-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Japanese holiday
        id: holiday
        run: |
          TODAY=$(date -u '+%Y-%m-%d' -d '+9 hours')  # JSTの日付
          echo "Today's date (JST): $TODAY"

          HOLIDAY=$(curl -s https://holidays-jp.github.io/api/v1/date.json | jq -r --arg d "$TODAY" '."$d"')
          if [ "$HOLIDAY" != "null" ]; then
            echo "Today is a holiday in Japan: $HOLIDAY"
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "skip=false" >> "$GITHUB_OUTPUT"

      - name: Login and verify UD System
        if: steps.holiday.outputs.skip == 'false'
        id: check
        env:
          BASE_URL: https://hu-udsystem.com/gateway/
          LOGIN_URL: https://hu-udsystem.com/gateway/logon/
          USERNAME: ${{ secrets.LOGIN_USERNAME }}
          PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: |
          echo "Fetching CSRF token..."
          CSRF=$(curl -s -c cookies.txt "$BASE_URL" | grep -oP '(?<=name="csrfmiddlewaretoken" value=").*?(?=")')
          if [ -z "$CSRF" ]; then
            echo "fail=true" >> "$GITHUB_OUTPUT"
            echo "reason=CSRF token not found" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Attempting login..."
          RESPONSE=$(curl -s -b cookies.txt -c cookies.txt \
            -d "csrfmiddlewaretoken=${CSRF}&user_id=${USERNAME}&pwd=${PASSWORD}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -e "$BASE_URL" \
            -X POST "$LOGIN_URL" \
            -w "HTTPSTATUS:%{http_code}")

          HTTP_CODE=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS\:.*//g')

          if [ "$HTTP_CODE" = "200" ] && echo "$BODY" | grep -q "ビルダー"; then
            echo "Login successful"
            echo "fail=false" >> "$GITHUB_OUTPUT"
          else
            echo "Login failed (HTTP $HTTP_CODE)"
            echo "fail=true" >> "$GITHUB_OUTPUT"
            echo "reason=HTTP $HTTP_CODE" >> "$GITHUB_OUTPUT"
          fi

      - name: Notify LINE if failed
        if: steps.check.outputs.fail == 'true'
        env:
          TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          TO: ${{ secrets.GROUP_ID }}
          REASON: ${{ steps.check.outputs.reason }}
        run: |
          MSG="本日、出勤の皆様へ\n\nお世話になっております。\nエラーにより、ビルダーが開かなくなっております。\n復旧次第再度お知らせいたします。\nそれまでは、自宅待機でお願いいたします。"
          BODY=$(jq -n --arg to "$TO" --arg msg "$MSG" \
            '{to:$to, messages:[{type:"text", text:$msg}]}')

          curl -sS -X POST "https://api.line.me/v2/bot/message/push" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            -d "$BODY"
            